// =============================================
//  students-data.js - Shared Student Records
// =============================================

const STUDENTS = [
  {
    id: 1,
    name: 'Julesjen Samonte',
    course: 'Information Technology',
    batch: '2025',
    initials: 'JS',
    badge: 'IT',
    badgeClass: 'badge-it',
    profileBadgeClass: 'profile-badge-it',
    code: 'IT &middot; 2026',
    avatar: 'images/julsjen-samonte.jpg',
    quote: 'Build small things with care, then keep building.',
    hobbies: ['UI design', 'Coding experiments', 'Campus events'],
    achievements: ['Capstone contributor', 'Peer programming mentor', 'Dean list candidate'],
    memories: ['Late-night debugging sessions', 'First successful system demo', 'BITS workshop day'],
    socials: '@julesjen.cs',
    portfolio: 'https://my-digital-portfolio--julesjensamonte.replit.app/',
    message: 'Thanks for being the classmate who made difficult projects feel possible.',
  },
  {
    id: 2,
    name: 'Christian Argonillo',
    course: 'Information Technology',
    batch: '2025',
    initials: 'CA',
    badge: 'IT',
    badgeClass: 'badge-it',
    profileBadgeClass: 'profile-badge-it',
    code: 'IT &middot; 3026',
    avatar: 'images/christian-argonillo.jpg',
    quote: 'Keep learning until the unfamiliar becomes useful.',
    hobbies: ['Networking labs', 'Gaming', 'Tech troubleshooting'],
    achievements: ['Systems support lead', 'Database project finalist', 'Team documentation lead'],
    memories: ['Group defense rehearsals', 'Helping classmates fix installations', 'First network lab pass'],
    socials: '@christian.it',
    facebook: 'https://www.facebook.com/Noctischx',
    portfolio: 'https://chwasabi.netlify.app/#',
    github: 'https://github.com/Chwasabiii',
    message: 'Your patience and practical mindset helped the group stay steady.',
  },
  {
    id: 3,
    name: 'Carl Christian Batalla',
    course: 'Information Technology',
    batch: '2025',
    initials: 'CB',
    badge: 'IT',
    badgeClass: 'badge-it',
    profileBadgeClass: 'profile-badge-it',
    code: 'IT &middot; 2026',
    avatar: 'images/christian-batalla.jpg',
    quote: 'Good ideas become real when someone starts wiring them together.',
    hobbies: ['Hardware builds', 'Robotics', 'Problem solving'],
    achievements: ['Prototype builder', 'Engineering project presenter', 'Lab assistant volunteer'],
    memories: ['Testing circuits before class', 'Team project crunch week', 'First working prototype'],
    socials: '@carl.eng',
    portfolio: null,
    message: 'You brought calm focus whenever the project needed a builder.',
  },
  {
    id: 4,
    name: 'Charles Delfin',
    course: 'Information Technology',
    batch: '2025',
    initials: 'CD',
    badge: 'IT',
    badgeClass: 'badge-it',
    profileBadgeClass: 'profile-badge-it',
    code: 'IT &middot; 2026',
    avatar: 'images/charles-delfin.jpg',
    quote: 'Patterns are everywhere if you take time to look.',
    hobbies: ['Data visualization', 'Basketball', 'Reading tech articles'],
    achievements: ['Analytics project presenter', 'Research group member', 'Dashboard designer'],
    memories: ['Cleaning messy datasets', 'Presentation practice runs', 'Class reporting day'],
    portfolio: 'https://sango-portfolio--charlesdelfin1.replit.app/',
    socials: '@charles.ds',
    message: 'You made numbers easier to understand and presentations easier to trust.',
  },
  {
    id: 5,
    name: 'Prince Christian Basor',
    course: 'Information Technology',
    batch: '2025',
    initials: 'PB',
    badge: 'IT',
    badgeClass: 'badge-it',
    profileBadgeClass: 'profile-badge-it',
    code: 'IT &middot; 2026',
    avatar: 'images/prince-bacor.jpg',
    quote: 'Connection matters, online and in real life.',
    hobbies: ['Network setup', 'Music', 'Mobile photography'],
    achievements: ['Network simulation lead', 'Class activity organizer', 'Tech support volunteer'],
    portfolio: 'https://makihoshina.netlify.app/',
    memories: ['Packet Tracer practice', 'Class photo day', 'Fixing setup issues before demos'],
    socials: '@prince.nt',
    message: 'You were the person people looked for when things had to connect.',
  },
  {
    id: 6,
    name: 'Professor',
    course: 'Information Technology',
    batch: '2026',
    initials: 'PR',
    badge: 'Professor',
    badgeClass: 'badge-gold',
    profileBadgeClass: 'profile-badge-gold',
    code: '*',
    avatar: null,
    highlighted: true,
    quote: 'Excellence is built one clear explanation at a time.',
    hobbies: ['Mentoring', 'Research', 'Reading'],
    portfolio: null,
    achievements: ['Salutatorian recognition', 'Class adviser favorite', 'Academic excellence award'],
    memories: ['Memorable lectures', 'Project consultations', 'Graduation preparation'],
    socials: '@professor.cs',
    message: 'Thank you for guiding the class with patience, clarity, and standards.',
  },
];
